from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "outputs/package/submission_manifest.md"
DEFAULT_OUTPUT = ROOT / "outputs/package/release_handoff.md"


def manifest_value(manifest_text: str, key: str) -> str:
    match = re.search(rf"^- {re.escape(key)}: `?([^`\n]+)`?$", manifest_text, re.MULTILINE)
    if not match:
        raise ValueError(f"manifest missing {key}")
    return match.group(1).strip()


def read_manifest_values(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    keys = [
        "payload_file_count",
        "total_payload_bytes",
        "zip_path",
        "zip_file_count",
        "zip_bytes",
        "zip_sha256",
    ]
    return {key: manifest_value(text, key) for key in keys}


def run_git(args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return result.stdout.strip()


def current_branch() -> str:
    return run_git(["branch", "--show-current"])


def render_handoff(values: dict[str, str], branch: str) -> str:
    zip_path = values["zip_path"]
    zip_sha = values["zip_sha256"]
    release_id = zip_sha[:12]
    return "\n".join(
        [
            "# Release Candidate Handoff",
            "",
            "This handoff is generated by `scripts/generate_release_handoff.py`.",
            "It is a repo-side handoff file and is intentionally not embedded inside the submission ZIP, so it can record the ZIP hash without creating a self-reference.",
            "",
            "## Release Candidate",
            "",
            f"- release_candidate_id: `{release_id}`",
            f"- zip_path: `{zip_path}`",
            f"- zip_sha256: `{zip_sha}`",
            f"- zip_bytes: {values['zip_bytes']}",
            f"- zip_file_count: {values['zip_file_count']}",
            f"- payload_file_count: {values['payload_file_count']}",
            f"- total_payload_bytes: {values['total_payload_bytes']}",
            f"- generated_branch: `{branch}`",
            "",
            "## Branch Rule",
            "",
            "- Work from `hbin`.",
            "- Keep `main` preserved as the protected/default branch.",
            "- Do not push development artifacts directly to `main`.",
            "- Commit SHA is intentionally verified by command after final push, not embedded in this tracked file.",
            "",
            "## Git Sync Check",
            "",
            "Run these after the release commit is pushed:",
            "",
            "```bash",
            "git status --short --branch",
            "git ls-remote --heads origin main hbin",
            "git log --oneline --decorate -3",
            "```",
            "",
            "Expected Git result:",
            "",
            "```text",
            "branch: hbin",
            "origin/main: present",
            "origin/hbin: present",
            "local hbin: not ahead/behind origin/hbin",
            "```",
            "",
            "## Local Freeze Commands",
            "",
            "Run these before uploading the ZIP:",
            "",
            "```bash",
            "python3 scripts/freeze_release_candidate.py --require-clean",
            "```",
            "",
            "Expected local result:",
            "",
            "```text",
            "package_manifest_integrity=passed",
            "release_handoff=repo-only/current",
            "tracked_worktree=clean",
            "external package link self-test status=pass",
            "freeze_status=pass",
            "```",
            "",
            "## External Upload Check",
            "",
            "After uploading the ZIP to the submission cloud, run:",
            "",
            "```bash",
            "python3 scripts/verify_external_package_link.py \"https://PUBLIC_DOWNLOAD_LINK\"",
            "```",
            "",
            "The external link is acceptable only when the verifier reports:",
            "",
            "```text",
            "status: pass",
            f"sha256: {zip_sha}",
            f"zip_file_count: {values['zip_file_count']}",
            f"bytes_read: {values['zip_bytes']}",
            "```",
            "",
            "## Remaining External Action",
            "",
            "- Upload the ZIP to the official submission location.",
            "- Verify the public link from a non-login or private browsing environment.",
            "- Run `scripts/verify_external_package_link.py` against that public link.",
            "",
        ]
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the release-candidate handoff sheet.")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    values = read_manifest_values(args.manifest)
    branch = current_branch()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_handoff(values, branch), encoding="utf-8")
    print(f"Wrote {args.output.relative_to(ROOT)}")
    print(f"release_candidate_id={values['zip_sha256'][:12]}")
    print(f"zip_sha256={values['zip_sha256']}")
    print(f"generated_branch={branch}")


if __name__ == "__main__":
    main()
